config/routes.rb
Rails.application.routes.draw do
  root to: "vehicles#index"
  resources :vehicles, only: [:index, :new, :create]
  resources :reservations, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :vehicle_category
  delegate :name, to: :vehicle_category, prefix: :category

  after_create :set_total_price

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :vehicle_category, presence: true
  validate :end_date_has_to_be_after_start_date
  validate :vehicle_available




  private

  def set_total_price
    update_attribute :total_price, vehicle_category.daily_price * (end_date - start_date).to_i
  end

  def end_date_has_to_be_after_start_date
    if end_date.present? && start_date.present? && end_date <= start_date
      errors.add(:end_date, "can't be before or on start date")
    end
  end

  def vehicle_available
    return unless vehicle_category && errors.blank?

    errors.add(:base, "#{category_name} not available to reserve #{start_date} to #{end_date}.") if conflicting_reservations.count >= vehicle_category.vehicles.count
  end

  def conflicting_reservations
    category_reservations = self.vehicle_category.reservations

    category_reservations.where(conflict_case_1).or(
      category_reservations.where(conflict_case_2).or(
        category_reservations.where(conflict_case_3).or(
          category_reservations.where(conflict_case_4)
        )
      )
    )
  end

  def conflict_case_1
    <<~EOS
      start_date <= '#{start_date}'
      AND end_date >= '#{start_date}'
    EOS
  end

  def conflict_case_2
    <<~EOS
      start_date <= '#{end_date}'
      AND end_date >= '#{end_date}'
    EOS
  end

  def conflict_case_3
    <<~EOS
      start_date <= '#{start_date}'
      AND end_date >= '#{end_date}'
    EOS
  end

  def conflict_case_4
    <<~EOS
      start_date > '#{start_date}'
      AND end_date < '#{end_date}'
    EOS
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_model
  delegate :make, :name, :vehicle_category, :category_name, :daily_price, to: :vehicle_model

  validates :commissioned_on, presence: true
end

app/models/vehicle_category.rb
class VehicleCategory < ApplicationRecord
  has_many :vehicle_models
  has_many :vehicles, through: :vehicle_models

  has_many :reservations
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_category
  has_many :vehicles

  delegate :name, to: :vehicle_category, prefix: :category
  delegate :daily_price, to: :vehicle_category

  def make_and_name
    "#{make} #{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :load_vehicle_categories, only: [:new, :create]

  def index
    @reservations = Reservation.all.order("start_date ASC")
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new reservation_params

    if @reservation.save
      redirect_to reservations_path
    else
      render action: "new"
    end
  end

  private
  def load_vehicle_categories
    @vehicle_categories = VehicleCategory.all
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :vehicle_category_id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :load_vehicle_models, only: [:new, :create]

  def index
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new vehicle_params

    if @vehicle.save
      redirect_to vehicles_path
    else
      render action: "new"
    end
  end

  private
  def load_vehicle_models
    @vehicle_models = VehicleModel.all
  end

  def vehicle_params
    params.require(:vehicle).permit(:year, :vehicle_model_id, :commissioned_on, :decommissioned_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentables</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <%= link_to "Vehicles", vehicles_path %>
        <%= link_to "Reservations", reservations_path %>
      </header>
      <section>
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>
  <% if @reservation.errors.any? %>
    <div class="errors">
      <% @reservation.errors.full_messages.each do |error_message| %>
        <p><%= error_message.to_s %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <%= label_tag :start_date %>
    <%= f.date_field :start_date %>
  </fieldset>

  <fieldset>
    <%= label_tag :end_date %>
    <%= f.date_field :end_date %>
  </fieldset>

  <fieldset>
    <%= label_tag :vehicle_category %>
    <%= f.collection_select :vehicle_category_id, @vehicle_categories, :id, :name, { include_blank: true } %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/reservations/index.html.erb
<h1>All Reservations</h1>
<table>
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Total Price</th>
      <th>Vehicle Category</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.start_date %></td>
        <td><%= reservation.end_date %></td>
        <td><%= number_to_currency(reservation.total_price) %></td>
        <td><%= reservation.category_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Add reservation", new_reservation_path %></p>

app/views/reservations/new.html.erb
<h1>Add reservation</h1>
<%= render partial: "form" %>

app/views/vehicles/_form.html.erb
<%= form_for @vehicle do |f| %>
  <% if @vehicle.errors.any? %>
    <div class="errors">
      <% @vehicle.errors.full_messages.each do |error_message| %>
        <p><%= error_message.to_s %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <%= label_tag :vehicle_model %>
    <%= f.collection_select :vehicle_model_id, @vehicle_models, :id, :make_and_name, { include_blank: true } %>
  </fieldset>

  <fieldset>
    <%= label_tag :year %>
    <%= f.select :year, (Date.today.year - 5)..(Date.today.year + 3), selected: Date.today.year %>
  </fieldset>

  <fieldset>
    <%= label_tag :commissioned_on %>
    <%= f.date_field :commissioned_on %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/vehicles/index.html.erb
<h1>All Vehicles</h1>
<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Category</th>
      <th>Daily Price</th>
      <th>Commissioned On</th>
      <th>Decommissioned On</th>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.category_name %></td>
        <td><%= number_to_currency(vehicle.daily_price) %></td>
        <td><%= vehicle.commissioned_on %></td>
        <td><%= vehicle.decommissioned_on %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Add vehicle", new_vehicle_path %></p>

app/views/vehicles/new.html.erb
<h1>Add vehicle</h1>
<%= render partial: "form" %>